# Generated by Django 5.2.3 on 2025-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('cnfrm_password', models.CharField(max_length=10)),
                ('DoB', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('profile', models.ImageField(upload_to='images/')),
                ('resume', models.FileField(upload_to='files/')),
            ],
        ),
    ]
