# Generated by Django 5.2.3 on 2025-06-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='DoB',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='cnfrm_password',
            new_name='confirmpassword',
        ),
    ]
